# This file is used to define services and their configurations
version: '3.9' # version of docker-compose

services:
  app: # service name
    build: # build context
      context: . # current directory
    ports: # port mapping
      - "8000:8000"
    volumes: # volume mapping for live reload
      - ./app:/app
    command: > # command to run
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"   
    environment:
      - DB_HOST=db
      - DB_NAME=recipe_app_db
      - DB_USER=admin
      - DB_PASS=admin
    depends_on:
      - db

  
  db: # service name
    image: postgres:13-alpine # image to use
    volumes:
      - dev-db-data:/var/lib/postgresql/data # volume mapping
    environment: # environment variables
      - POSTGRES_DB=recipe_app_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    
volumes:
  dev-db-data: # volume name


