# Generated by Django 4.2.17 on 2025-02-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='names',
            new_name='name',
        ),
    ]
