# this file is used to run the checks on the codebase using GitHub Actions
---
name: Checks # name of the workflow

on: ['push'] # event that triggers the workflow

jobs: # jobs to run
  test-lint: # job name
    name: Test # name of the job
    runs-on: ubuntu-20.04 # runner to use here we use ubuntu 20.04 other options are windows-latest, macos-latest
    steps: # steps to run
      - name: Login to Docker hub # name of the step
        uses: docker/login-action@v1 # action to checkout the codebase
        with: # inputs for the action
          username: ${{ secrets.DIVYESH3489 }} # username for docker hub
          password: ${{ secrets.DOCKERHUB_TOKEN }} # password for docker hub
      - name: Checkout code # name of the step
        uses: actions/checkout@v2 # action to check
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Test # name of the step
        run: docker-compose run app sh -c "python manage.py test" # command to run